#!/usr/bin/env python3
"""
主构建脚本 — 协调所有子脚本，完成规则集全自动构建。

整体架构:
    ┌──────────────────────────────────────────────────────────────────┐
    │                     build.py (主协调器)                          │
    │                                                                  │
    │  1. 下载 manual_*.txt ─────────────────────→ tmp/                │
    │  2. ad_extractor.py  ─→ tmp/ad_domains.txt + tmp/ad_ips.txt     │
    │     (EasyList + 乘风 + Peter Lowe → 解析 Adblock Plus 格式)      │
    │  3. gfw_parser.py    ─→ tmp/gfw_domains.txt                     │
    │     (GFWList base64 解码 + cn-blocked-domain → 纯域名)           │
    │  4. clash_builder.py ─→ rules/*.yaml + rules/*.txt              │
    │     (中间产物 + manual 文件 → 7 组规则集)                         │
    │  5. 生成 timestamp.txt                                           │
    │  6. 清理 tmp/ (除非 --keep-tmp)                                   │
    └──────────────────────────────────────────────────────────────────┘

执行流程：
  1. 创建 tmp/ 目录
  2. 下载 manual_*.txt 手动规则文件到 tmp/
  3. 运行 ad_extractor.py → 生成 ad_domains.txt + ad_ips.txt
  4. 运行 gfw_parser.py → 生成 gfw_domains.txt（需 manual_gfwlist_excludes.txt）
  5. 运行 clash_builder.py → 生成所有规则集文件
  6. 生成 timestamp.txt
  7. 清理 tmp/ 目录（除非 --keep-tmp）

支持命令行参数：
  --output-dir: 输出目录（默认 ../rules）
  --keep-tmp: 保留临时文件（调试用）

零第三方依赖，仅使用 Python 标准库。
"""

import os
import sys
import time
from datetime import datetime, timezone, timedelta

# 确保能 import 同目录下的子脚本
_SCRIPT_DIR = os.path.dirname(os.path.abspath(__file__))
if _SCRIPT_DIR not in sys.path:
    sys.path.insert(0, _SCRIPT_DIR)

import ad_extractor
import gfw_parser
import clash_builder

# ---------------------------------------------------------------------------
# 配置
# ---------------------------------------------------------------------------

# 手动规则文件 URL 前缀（见需求文档 3.3 节）
MANUAL_URL_PREFIX = (
    "https://raw.githubusercontent.com/Johnshall/"
    "Shadowrocket-ADBlock-Rules-Forever/build/factory/"
)

# 需要下载的手动规则文件列表
MANUAL_FILES = [
    "manual_reject.txt",
    "manual_proxy.txt",
    "manual_direct.txt",
    "manual_gfwlist.txt",
    "manual_gfwlist_excludes.txt",
]


# ---------------------------------------------------------------------------
# 手动文件下载
# ---------------------------------------------------------------------------

def download_manual_files(tmp_dir):
    """
    下载所有手动规则文件到 tmp/ 目录。

    使用 ad_extractor.download_text 函数（支持重试）。
    单个文件失败不阻塞。
    """
    print("\n--- 下载手动规则文件 ---")

    for filename in MANUAL_FILES:
        url = MANUAL_URL_PREFIX + filename
        dest = os.path.join(tmp_dir, filename)

        print(f"  下载 {filename}...")
        content = ad_extractor.download_text(url)
        if content is None:
            print(f"  [ERROR] 下载失败: {filename}")
            continue

        with open(dest, "w", encoding="utf-8") as f:
            f.write(content)
        print(f"  {filename} ({len(content)} 字节)")

    print("手动规则文件下载完成。")


# ---------------------------------------------------------------------------
# 时间戳生成
# ---------------------------------------------------------------------------

def generate_timestamp(output_dir, total_sources):
    """
    生成 timestamp.txt 文件，记录构建时间和数据源信息。

    参数:
        output_dir: 输出目录
        total_sources: 数据源总数
    """
    tz_cst = timezone(timedelta(hours=8))
    now_str = datetime.now(tz_cst).strftime("%Y-%m-%d %H:%M:%S CST")

    ts_path = os.path.join(output_dir, "timestamp.txt")
    with open(ts_path, "w", encoding="utf-8") as f:
        f.write(f"Rule sets last updated: {now_str}\n")
        f.write(f"Source: raw data sources (v2 direct build)\n")
        f.write(f"Manual files: {MANUAL_URL_PREFIX}\n")
        f.write(f"Generated by: build.py (v2)\n")

    print(f"\n  timestamp.txt ({now_str})")


# ---------------------------------------------------------------------------
# 主函数
# ---------------------------------------------------------------------------

def main():
    """主函数：协调整个构建流程。"""
    import argparse

    parser = argparse.ArgumentParser(
        description="主构建脚本 — 协调所有子脚本完成规则集构建")
    parser.add_argument(
        "--output-dir",
        default=os.path.join(_SCRIPT_DIR, "..", "rules"),
        help="输出目录（默认: ../rules）")
    parser.add_argument(
        "--keep-tmp",
        action="store_true",
        help="保留临时文件（调试用）")
    args = parser.parse_args()

    output_dir = os.path.abspath(args.output_dir)
    tmp_dir = os.path.join(_SCRIPT_DIR, "..", "tmp")

    print("=" * 64)
    print(" 规则集构建器 (build.py) — v2 直接构建")
    print("=" * 64)

    # --- 1. 准备 tmp/ 目录 ---
    print("\n--- 准备临时目录 ---")
    os.makedirs(tmp_dir, exist_ok=True)
    print(f"  tmp/ = {tmp_dir}")

    # --- 2. 下载手动规则文件（gfw_parser 需要 excludes 文件）---
    download_manual_files(tmp_dir)

    # --- 3. 运行广告规则提取器 ---
    print("\n" + "=" * 64)
    ad_extractor.main(tmp_dir=tmp_dir)

    # --- 4. 运行 GFWList 解析器 ---
    print("\n" + "=" * 64)
    gfw_parser.main(tmp_dir=tmp_dir)

    # --- 5. 运行 Clash 规则集构建器 ---
    print("\n" + "=" * 64)
    clash_builder.main(tmp_dir=tmp_dir, output_dir=output_dir)

    # --- 6. 生成时间戳 ---
    print("\n--- 生成时间戳 ---")
    generate_timestamp(output_dir, len(ad_extractor.AD_SOURCES))

    # --- 7. 清理临时目录 ---
    if args.keep_tmp:
        print(f"\n[INFO] 保留临时文件: {tmp_dir}")
    else:
        print(f"\n--- 清理临时目录 ---")
        try:
            for filename in os.listdir(tmp_dir):
                file_path = os.path.join(tmp_dir, filename)
                if os.path.isfile(file_path):
                    os.remove(file_path)
            os.rmdir(tmp_dir)
            print(f"  已清理 {tmp_dir}")
        except OSError as exc:
            print(f"  [WARN] 清理失败: {exc}", file=sys.stderr)

    print("\n" + "=" * 64)
    print(" 构建完成！")
    print(f" 输出目录: {output_dir}")
    print("=" * 64)


if __name__ == "__main__":
    main()
